# Generated by Django 5.1.10 on 2026-05-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aceptacion', 'Aceptación de invitación'), ('rechazo', 'Rechazo de invitación'), ('evaluacion', 'Evaluación creada/completada'), ('resultado', 'Resultado publicado'), ('sistema', 'Sistema'), ('otro', 'Otro')], default='sistema', max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('leida', 'Leída'), ('archivada', 'Archivada')], default='pendiente', max_length=20)),
                ('url_relacionada', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
