# Generated by Django 5.1.10 on 2026-05-21 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=60, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, default="")),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Fase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField(unique=True)),
                ("nombre", models.CharField(blank=True, default="", max_length=120)),
            ],
            options={
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="GAES",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("descripcion", models.TextField(blank=True, default="")),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "GAES",
                "verbose_name_plural": "GAES",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Aprendiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documento", models.CharField(max_length=20, unique=True)),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("programa", models.CharField(blank=True, default="", max_length=100)),
                ("trimestre", models.CharField(blank=True, max_length=10)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("direccion", models.TextField(blank=True)),
                ("bloqueado", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "propietario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aprendices_propietario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aprendiz",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aprendices",
                        to="evaluacion.fase",
                    ),
                ),
            ],
            options={
                "ordering": ["nombres"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criterio", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("puntaje_maximo", models.IntegerField(default=10)),
                ("orden", models.IntegerField(default=0)),
                ("etapa", models.CharField(blank=True, max_length=50)),
                (
                    "checklist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="evaluacion.checklist",
                    ),
                ),
                (
                    "competencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="evaluacion.competencia",
                    ),
                ),
            ],
            options={
                "ordering": ["competencia__codigo", "orden"],
            },
        ),
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "calificacion_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "aprendiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="evaluacion.aprendiz",
                    ),
                ),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="evaluacion.checklist",
                    ),
                ),
                (
                    "juror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddField(
            model_name="competencia",
            name="fase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="competencias",
                to="evaluacion.fase",
            ),
        ),
        migrations.CreateModel(
            name="Ficha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=30, unique=True)),
                ("programa", models.CharField(blank=True, default="", max_length=200)),
                (
                    "jornada",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mañana", "Mañana"),
                            ("tarde", "Tarde"),
                            ("noche", "Noche"),
                            ("mixto", "Mixto"),
                        ],
                        default="mañana",
                        max_length=50,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("finalizado", "Finalizado"),
                            ("suspendido", "Suspendido"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fichas_asignadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gaes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fichas",
                        to="evaluacion.gaes",
                    ),
                ),
            ],
            options={
                "ordering": ["numero"],
            },
        ),
        migrations.AddField(
            model_name="competencia",
            name="ficha",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="competencias",
                to="evaluacion.ficha",
            ),
        ),
        migrations.AddField(
            model_name="aprendiz",
            name="ficha",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aprendices",
                to="evaluacion.ficha",
            ),
        ),
        migrations.AddField(
            model_name="competencia",
            name="gaes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="competencias",
                to="evaluacion.gaes",
            ),
        ),
        migrations.AddField(
            model_name="aprendiz",
            name="gaes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aprendices",
                to="evaluacion.gaes",
            ),
        ),
        migrations.CreateModel(
            name="Invitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                ("fecha_evaluacion", models.DateField(blank=True, null=True)),
                ("hora_evaluacion", models.TimeField(blank=True, null=True)),
                ("mensaje", models.TextField(blank=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitaciones_enviadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instructor_invitado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitaciones_recibidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_envio"],
            },
        ),
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promedio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "calificacion_final",
                    models.CharField(default="No evaluado", max_length=10),
                ),
                ("fecha_cierre", models.DateTimeField(auto_now_add=True)),
                ("observaciones_generales", models.TextField(blank=True)),
                (
                    "aprendiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="evaluacion.aprendiz",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_cierre"],
            },
        ),
        migrations.CreateModel(
            name="Trimestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField()),
                ("nombre", models.CharField(blank=True, default="", max_length=120)),
                ("anio", models.PositiveIntegerField(blank=True, null=True)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-anio", "numero"],
                "unique_together": {("numero", "anio")},
            },
        ),
        migrations.CreateModel(
            name="ResultadoAprendizaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=60, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, default="")),
                (
                    "trimestre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resultados_aprendizaje",
                        to="evaluacion.trimestre",
                    ),
                ),
            ],
            options={
                "ordering": ["codigo"],
            },
        ),
        migrations.AddField(
            model_name="ficha",
            name="trimestre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fichas",
                to="evaluacion.trimestre",
            ),
        ),
        migrations.AddField(
            model_name="competencia",
            name="trimestre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competencias",
                to="evaluacion.trimestre",
            ),
        ),
        migrations.CreateModel(
            name="EvaluacionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje", models.IntegerField(default=0)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="evaluacion.evaluacion",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluacion.checklistitem",
                    ),
                ),
            ],
            options={
                "unique_together": {("evaluacion", "item")},
            },
        ),
    ]
