# Generated by Django 5.2.14 on 2026-05-22 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluacion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competencia",
            name="gaes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="competencias",
                to="evaluacion.gaes",
            ),
        ),
    ]
