# Generated by Django 5.2.14 on 2026-05-22 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluacion", "0002_make_gaes_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="gaes",
            name="ficha",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grupos",
                to="evaluacion.ficha",
            ),
        ),
        migrations.AlterField(
            model_name="gaes",
            name="nombre",
            field=models.CharField(max_length=120),
        ),
    ]
