# Generated by Django 5.2.14 on 2026-05-25 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluacion", "0003_gaes_ficha_alter_gaes_nombre"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invitacion",
            name="ficha",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitaciones",
                to="evaluacion.ficha",
            ),
        ),
        migrations.AddField(
            model_name="invitacion",
            name="instructores_jurados",
            field=models.ManyToManyField(
                blank=True,
                related_name="invitaciones_como_jurado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
