# Generated by Django 5.2.14 on 2026-05-27 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluacion", "0004_invitacion_ficha_invitacion_instructores_jurados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aprendiz",
            name="ficha",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aprendices",
                to="evaluacion.ficha",
            ),
        ),
    ]
