# Generated by Django 5.2.14 on 2026-05-27 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluacion", "0006_alter_gaes_ficha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competencia",
            name="ficha",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competencias",
                to="evaluacion.ficha",
            ),
        ),
    ]
