# Generated by Django 5.2.14 on 2026-05-30 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluacion", "0007_alter_competencia_ficha"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitacion",
            name="checklist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitaciones",
                to="evaluacion.checklist",
            ),
        ),
    ]
