# Generated by Django 5.2.14 on 2026-06-21 01:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluacion", "0008_add_checklist_to_invitacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklist",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
