# Generated by Django 5.2.14 on 2026-05-22 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("evaluacion", "0003_gaes_ficha_alter_gaes_nombre"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BitacoraEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("estado_anterior", models.CharField(blank=True, max_length=30)),
                ("estado_nuevo", models.CharField(blank=True, max_length=30)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bitacora",
                        to="evaluacion.evaluacion",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cambios_evaluacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitácora de Evaluación",
                "verbose_name_plural": "Bitácoras de Evaluación",
                "ordering": ["-created_at"],
                "unique_together": {("evaluacion", "version")},
            },
        ),
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("usuarios", "Usuarios"),
                            ("aprendices", "Aprendices"),
                            ("evaluacion", "Evaluación"),
                            ("checklists", "Checklists"),
                            ("resultados", "Resultados"),
                            ("invitaciones", "Invitaciones"),
                            ("notificaciones", "Notificaciones"),
                            ("reportes", "Reportes"),
                            ("fichas", "Fichas"),
                            ("competencias", "Competencias"),
                            ("gaes", "GAES"),
                            ("trimestres", "Trimestres"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("crear", "Crear"),
                            ("editar", "Editar"),
                            ("eliminar", "Eliminar"),
                            ("importar", "Importar"),
                            ("exportar", "Exportar"),
                            ("aprobar", "Aprobar"),
                            ("rechazar", "Rechazar"),
                            ("bloquear", "Bloquear"),
                            ("desbloquear", "Desbloquear"),
                            ("iniciar_eval", "Iniciar Evaluación"),
                            ("finalizar_eval", "Finalizar Evaluación"),
                            ("reevaluar", "Re-Evaluación"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("objeto_id", models.CharField(blank=True, max_length=30)),
                ("objeto_tipo", models.CharField(blank=True, max_length=60)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoría",
                "verbose_name_plural": "Logs de Auditoría",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["modulo", "created_at"],
                        name="auditoria_l_modulo_7e389a_idx",
                    ),
                    models.Index(
                        fields=["usuario", "created_at"],
                        name="auditoria_l_usuario_fc4f1c_idx",
                    ),
                    models.Index(
                        fields=["accion", "created_at"],
                        name="auditoria_l_accion_93e45e_idx",
                    ),
                ],
            },
        ),
    ]
